name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Test
        run: docker run --network container:docker-php appropriate/curl -s --retry 10 --retry-connrefused http://localhost:80/prueba.html
